from pathlib import Path
import pandas as pd

### Load samples.tsv file and obtain list of samples ###
SAMPLE_TABLE = pd.read_csv(config["input"]["sample table"], index_col="sample", sep="\t")
SAMPLE_TABLE.index = SAMPLE_TABLE.index.map(str)  # convert index (samples) to string 
SAMPLES = SAMPLE_TABLE.index.tolist()  # obtain list of samples 

##### Define intermediate/results files/directories #####
scratch_dir = Path(config["scratch directory"])
results_dir = Path(config["results directory"])

Path(scratch_dir).mkdir(exist_ok=True, parents=True)
Path(results_dir).mkdir(exist_ok=True, parents=True)

scratch_dict = {
    "read_mapping": scratch_dir / "read_mapping", 
    "microbemod_call_methylation": scratch_dir / "microbemod_call_methylation", 
}

results_dict = {
    'TEMP': results_dir / "TEMP.tsv", 
}

##### Define output files to generate #####
rule all:
    input:
        expand(scratch_dict['microbemod_call_methylation'] / "{sample}_motifs.tsv", sample=SAMPLES), 
        # expand(scratch_dict["read_mapping"] / "{sample}_sorted.bam", sample=SAMPLES), 


##### Import all .smk rule files #####
for smk_file in Path('workflow/rules').glob('*smk'):
    include: str(smk_file).replace('workflow/', '') 